import { ModelJSON, StyleType, IController, IHooks, IModel, WorksheetType, IWindowSize, ScrollValue, IRange, ResultType, DrawingElement, IPosition, DefinedNameItem, WorksheetData, EMergeCellType, AutoFilterItem, CanvasOverlayPosition, ControllerEventEmitterType } from '../types';
import { EventEmitter } from '../util';
export declare class Controller extends EventEmitter<ControllerEventEmitterType> implements IController {
    private scrollValue;
    readonly model: IModel;
    private changeSet;
    private floatElementUuid;
    private copyRange;
    private isCut;
    private readonly hooks;
    private sheetViewSize;
    private readonly;
    private canvasSize;
    constructor(model: IModel, hooks: IHooks);
    setReadOnly(readOnly: boolean): void;
    getReadOnly(): boolean;
    setCanvasSize(size: CanvasOverlayPosition): void;
    getCanvasSize(): CanvasOverlayPosition;
    private setSheetViewSize;
    getSheetViewSize(): IWindowSize;
    getHeaderSize(): {
        width: number;
        height: number;
    };
    clearHistory(): void;
    getHooks(): IHooks;
    validateDefinedName(name: string): boolean;
    validateDrawing(item: DrawingElement): boolean;
    validateRange(range: IRange): boolean;
    getCurrentSheetId(): string;
    getSheetList(): WorksheetType[];
    getSheetInfo(sheetId?: string): WorksheetType | undefined;
    transaction: <T>(fn: () => T, origin?: any) => T;
    emitChange(): void;
    getActiveRange(r?: IRange): import('..').ActiveRange;
    setNextActiveCell(direction: 'left' | 'right' | 'down' | 'up'): void;
    setActiveRange(range: IRange): void;
    setCurrentSheetId(id: string): void;
    getWorksheet(sheetId?: string): WorksheetData;
    setWorksheet(data: WorksheetData): void;
    addSheet(): WorksheetType | undefined;
    addFirstSheet(): WorksheetType | undefined;
    deleteSheet(sheetId?: string): void;
    updateSheetInfo(data: Partial<WorksheetType>, sheetId?: string): void;
    hideSheet(sheetId?: string): void;
    unhideSheet(sheetId: string): void;
    renameSheet(sheetName: string, sheetId?: string): void;
    fromJSON(json: ModelJSON): void;
    toJSON(): ModelJSON;
    setCell(value: ResultType[][], style: Array<Array<Partial<StyleType>>>, range: IRange): void;
    deleteCell(range: IRange): void;
    setCellValue(value: ResultType, range: IRange): void;
    updateCellStyle(style: Partial<StyleType>, range: IRange): void;
    getCell: (range: IRange) => import('..').ModelCellType | undefined;
    canRedo(): boolean;
    canUndo(): boolean;
    undo(): void;
    redo(): void;
    getCol(col: number, sheetId?: string): import('..').CustomItem;
    getColWidth(col: number, sheetId?: string): number;
    setColWidth(col: number, width: number, sheetId?: string): void;
    getRow(row: number, sheetId?: string): import('..').CustomItem;
    getRowHeight(row: number, sheetId?: string): number;
    setRowHeight(row: number, height: number, sheetId?: string): void;
    getCellSize(range: IRange): IWindowSize;
    private getRangeSize;
    computeCellPosition(range: IRange): IPosition;
    addRow(rowIndex: number, count: number, isAbove?: boolean): void;
    addCol(colIndex: number, count: number, isRight?: boolean): void;
    deleteCol(colIndex: number, count: number): void;
    deleteRow(rowIndex: number, count: number): void;
    hideCol(colIndex: number, count: number): void;
    hideRow(rowIndex: number, count: number): void;
    unhideRow(rowIndex: number, count: number): void;
    unhideCol(colIndex: number, count: number): void;
    getScroll(sheetId?: string): ScrollValue;
    setScroll(data: ScrollValue, sheetId?: string): void;
    private getPasteRange;
    private parseText;
    private parseHTML;
    private getCopyData;
    private pasteFloatElement;
    paste(event?: ClipboardEvent): Promise<void>;
    private basePaste;
    copy(event?: ClipboardEvent): Promise<void>;
    cut(event?: ClipboardEvent): Promise<void>;
    private baseCopy;
    getCopyRange(): IRange | undefined;
    setCopyRange(range: IRange | undefined): void;
    deleteAll(sheetId?: string): void;
    getDefineName(range: IRange): string;
    getDefineNameList(): DefinedNameItem[];
    setDefineName(range: IRange, name: string): boolean;
    checkDefineName(name: string): IRange | undefined;
    getDrawingList(sheetId?: string): DrawingElement[];
    addDrawing(...data: DrawingElement[]): void;
    updateDrawing(uuid: string, value: Partial<DrawingElement>): void;
    deleteDrawing(uuid: string): void;
    getMergeCellList(sheetId?: string): IRange[];
    addMergeCell(range: IRange, type?: EMergeCellType): void;
    deleteMergeCell(range: IRange): void;
    setFloatElementUuid(uuid: string): void;
    getFilter(sheetId?: string): AutoFilterItem | undefined;
    addFilter(range: IRange): void;
    deleteFilter(sheetId?: string): void;
    updateFilter(sheetId: string, value: Partial<AutoFilterItem>): void;
}
