import { BorderType, ChartType } from '../types';
export declare const DEFAULT_FONT_SIZE = 12;
export declare const MUST_FONT_FAMILY = "sans-serif";
export declare const SHEET_NAME_PREFIX = "Sheet";
export declare const CELL_HEIGHT = 22;
export declare const CELL_WIDTH = 76;
export declare const ROW_TITLE_HEIGHT = 22;
export declare const COL_TITLE_WIDTH: number;
export declare const HIDE_CELL = 0;
export declare const TEXTAREA_MAX_ROWS = 10;
export declare const MERGE_CELL_LINE_BREAK = "&#10;";
export declare const LINE_BREAK = "\n";
export declare const CSV_SPLITTER = ",";
export declare const XLSX_MAX_COL_COUNT = 16384;
export declare const XLSX_MAX_ROW_COUNT = 1048576;
export declare const DEFAULT_ROW_COUNT = 200;
export declare const MAX_ADD_ROW_THRESHOLD = 200;
export declare const DEFAULT_COL_COUNT = 30;
export declare const DEFAULT_POSITION = -999;
export declare const FILTER_RECT_SIZE = 16;
export declare const SHEET_ITEM_TEST_ID_PREFIX = "__sheet_item_";
export declare const FORMULA_PREFIX = "=";
export declare const SPLITTER = "_";
export declare const MAX_NAME_LENGTH = 35;
export declare const MAX_PARAMS_COUNT = 256;
export declare const FORMULA_MAX_PRECISION = 9;
export declare const FORMULA_EDITOR_ROLE = "__FORMULA_EDITOR_ROLE__";
export declare const DEFAULT_FORMAT_CODE = "General";
export declare const DEFAULT_TEXT_FORMAT_CODE = "@";
export declare const RTL_LANGUAGE_LIST: readonly ["ar-EG", "ar-SA"];
export declare const LANGUAGE_LIST: readonly ["en-US", "zh-CN", "fr-FR", "zh-HK", "ja-JP", "ko-KR", "es-ES", "de-DE", "it-IT", "pt-BR", "pt-PT", "nl-NL", "ar-EG", "ar-SA"];
export declare const TEXT_FLAG: "#GETTING_DATA";
export declare const ERROR_SET: Set<"#GETTING_DATA" | "#DIV/0!" | "#NULL!" | "#NUM!" | "#REF!" | "#VALUE!" | "#N/A" | "#NAME?">;
export type ErrorTypes = typeof ERROR_SET extends Set<infer T> ? T : never;
export declare const DEFAULT_LINE_WIDTH = 1;
export declare const BORDER_TYPE_MAP: Record<BorderType, number>;
export declare const COLOR_PICKER_COLOR_LIST: string[];
export declare const CELL_REG_EXP: RegExp;
export declare const COLUMN_REG_EXP: RegExp;
export declare const ROW_REG_EXP: RegExp;
export declare const DEFINED_NAME_REG_EXP: RegExp;
export declare const BUILT_IN_FUNCTION_SET: Set<"ABS" | "ACCRINT" | "ACCRINTM" | "ACOS" | "ACOSH" | "ACOT" | "ACOTH" | "ADDRESS" | "AGGREGATE" | "AMORDEGRC" | "AMORLINC" | "AND" | "ARABIC" | "AREAS" | "ARRAYTOTEXT" | "ASC" | "ASIN" | "ASINH" | "ATAN" | "ATAN2" | "ATANH" | "AVEDEV" | "AVERAGE" | "AVERAGEA" | "AVERAGEIF" | "AVERAGEIFS" | "BAHTTEXT" | "BASE" | "BESSELI" | "BESSELJ" | "BESSELK" | "BESSELY" | "BETA.DIST" | "BETA.INV" | "BETADIST" | "BETAINV" | "BIN2DEC" | "BIN2HEX" | "BIN2OCT" | "BINOM.DIST" | "BINOM.DIST.RANGE" | "BINOM.INV" | "BINOMDIST" | "BITAND" | "BITLSHIFT" | "BITOR" | "BITRSHIFT" | "BITXOR" | "CALL" | "CEILING" | "CEILING.MATH" | "CEILING.PRECISE" | "CELL" | "CHAR" | "CHIDIST" | "CHIINV" | "CHISQ.DIST" | "CHISQ.DIST.RT" | "CHISQ.INV" | "CHISQ.INV.RT" | "CHISQ.TEST" | "CHITEST" | "CLEAN" | "CODE" | "COLUMN" | "COLUMNS" | "COMBIN" | "COMBINA" | "COMPLEX" | "CONCAT" | "CONCATENATE" | "CONFIDENCE" | "CONFIDENCE.NORM" | "CONFIDENCE.T" | "CONVERT" | "CORREL" | "COS" | "COSH" | "COT" | "COTH" | "COUNT" | "COUNTA" | "COUNTBLANK" | "COUNTIF" | "COUNTIFS" | "COUPDAYBS" | "COUPDAYS" | "COUPDAYSNC" | "COUPNCD" | "COUPNUM" | "COUPPCD" | "COVAR" | "COVARIANCE.P" | "COVARIANCE.S" | "CRITBINOM" | "CSC" | "CSCH" | "CUBEKPIMEMBER" | "CUBEMEMBER" | "CUBEMEMBERPROPERTY" | "CUBERANKEDMEMBER" | "CUBESET" | "CUBESETCOUNT" | "CUBEVALUE" | "CUMIPMT" | "CUMPRINC" | "DATE" | "DATEDIF" | "DATEVALUE" | "DAVERAGE" | "DAY" | "DAYS" | "DAYS360" | "DB" | "DBCS" | "DCOUNT" | "DCOUNTA" | "DDB" | "DEC2BIN" | "DEC2HEX" | "DEC2OCT" | "DECIMAL" | "DEGREES" | "DELTA" | "DEVSQ" | "DGET" | "DISC" | "DMAX" | "DMIN" | "DOLLAR" | "DOLLARDE" | "DOLLARFR" | "DPRODUCT" | "DSTDEV" | "DSTDEVP" | "DSUM" | "DURATION" | "DVAR" | "DVARP" | "EDATE" | "EFFECT" | "ENCODEURL" | "EOMONTH" | "ERF" | "ERF.PRECISE" | "ERFC" | "ERFC.PRECISE" | "ERROR.TYPE" | "EUROCONVERT" | "EVEN" | "EXACT" | "EXP" | "EXPON.DIST" | "EXPONDIST" | "F.DIST" | "F.DIST.RT" | "F.INV" | "F.INV.RT" | "F.TEST" | "FACT" | "FACTDOUBLE" | "FALSE" | "FDIST" | "FILTER" | "FILTERXML" | "FIND" | "FINDB" | "FINV" | "FISHER" | "FISHERINV" | "FIXED" | "FLOOR" | "FLOOR.MATH" | "FLOOR.PRECISE" | "FORECAST" | "FORECAST.ETS" | "FORECAST.ETS.CONFINT" | "FORECAST.ETS.SEASONALITY" | "FORECAST.ETS.STAT" | "FORECAST.LINEAR" | "FORMULATEXT" | "FREQUENCY" | "FTEST" | "FV" | "FVSCHEDULE" | "GAMMA" | "GAMMA.DIST" | "GAMMA.INV" | "GAMMADIST" | "GAMMAINV" | "GAMMALN" | "GAMMALN.PRECISE" | "GAUSS" | "GCD" | "GEOMEAN" | "GESTEP" | "GETPIVOTDATA" | "GROWTH" | "HARMEAN" | "HEX2BIN" | "HEX2DEC" | "HEX2OCT" | "HLOOKUP" | "HOUR" | "HYPERLINK" | "HYPGEOM.DIST" | "HYPGEOMDIST" | "IFERROR" | "IFNA" | "IFS" | "IMABS" | "IMAGINARY" | "IMARGUMENT" | "IMCONJUGATE" | "IMCOS" | "IMCOSH" | "IMCOT" | "IMCSC" | "IMCSCH" | "IMDIV" | "IMEXP" | "IMLN" | "IMLOG10" | "IMLOG2" | "IMPOWER" | "IMPRODUCT" | "IMREAL" | "IMSEC" | "IMSECH" | "IMSIN" | "IMSINH" | "IMSQRT" | "IMSUB" | "IMSUM" | "IMTAN" | "INFO" | "INT" | "INTERCEPT" | "INTRATE" | "IPMT" | "IRR" | "ISBLANK" | "ISERR" | "ISERROR" | "ISEVEN" | "ISFORMULA" | "ISLOGICAL" | "ISNA" | "ISNONTEXT" | "ISNUMBER" | "ISO.CEILING" | "ISODD" | "ISOWEEKNUM" | "ISPMT" | "ISREF" | "ISTEXT" | "JIS" | "KURT" | "LARGE" | "LCM" | "LEFT" | "LEFTB" | "LEN" | "LENB" | "LET" | "LINEST" | "LN" | "LOG" | "LOG10" | "LOGEST" | "LOGINV" | "LOGNORM.DIST" | "LOGNORM.INV" | "LOGNORMDIST" | "LOOKUP" | "LOWER" | "MATCH" | "MAX" | "MAXA" | "MAXIFS" | "MDETERM" | "MDURATION" | "MEDIAN" | "MID" | "MIDB" | "MIN" | "MINA" | "MINIFS" | "MINUTE" | "MINVERSE" | "MIRR" | "MMULT" | "MOD" | "MODE" | "MODE.MULT" | "MODE.SNGL" | "MONTH" | "MROUND" | "MULTINOMIAL" | "MUNIT" | "N" | "NA" | "NEGBINOM.DIST" | "NEGBINOMDIST" | "NETWORKDAYS" | "NETWORKDAYS.INTL" | "NOMINAL" | "NORM.DIST" | "NORM.INV" | "NORM.S.DIST" | "NORM.S.INV" | "NORMDIST" | "NORMINV" | "NORMSDIST" | "NORMSINV" | "NOT" | "NOW" | "NPER" | "NPV" | "NUMBERVALUE" | "OCT2BIN" | "OCT2DEC" | "OCT2HEX" | "ODD" | "ODDFPRICE" | "ODDFYIELD" | "ODDLPRICE" | "ODDLYIELD" | "OR" | "PDURATION" | "PEARSON" | "PERCENTILE" | "PERCENTILE.EXC" | "PERCENTILE.INC" | "PERCENTRANK" | "PERCENTRANK.EXC" | "PERCENTRANK.INC" | "PERMUT" | "PERMUTATIONA" | "PHI" | "PHONETIC" | "PI" | "PMT" | "POISSON" | "POISSON.DIST" | "POWER" | "PPMT" | "PRICE" | "PRICEDISC" | "PRICEMAT" | "PROB" | "PRODUCT" | "PROPER" | "PV" | "QUARTILE" | "QUARTILE.EXC" | "QUARTILE.INC" | "QUOTIENT" | "RADIANS" | "RAND" | "RANDARRAY" | "RANDBETWEEN" | "RANK" | "RANK.AVG" | "RANK.EQ" | "RATE" | "RECEIVED" | "REGISTER.ID" | "REPLACE" | "REPLACEB" | "REPT" | "RIGHT" | "RIGHTB" | "ROMAN" | "ROUND" | "ROUNDDOWN" | "ROUNDUP" | "ROW" | "ROWS" | "RRI" | "RSQ" | "RTD" | "SEARCH" | "SEARCHB" | "SEC" | "SECH" | "SECOND" | "SEQUENCE" | "SERIESSUM" | "SHEET" | "SHEETS" | "SIGN" | "SIN" | "SINH" | "SKEW" | "SKEW.P" | "SLN" | "SLOPE" | "SMALL" | "SORT" | "SORTBY" | "SQRT" | "SQRTPI" | "STANDARDIZE" | "STDEV" | "STDEV.P" | "STDEV.S" | "STDEVA" | "STDEVP" | "STDEVPA" | "STEYX" | "SUBSTITUTE" | "SUBTOTAL" | "SUM" | "SUMIF" | "SUMIFS" | "SUMPRODUCT" | "SUMSQ" | "SUMX2MY2" | "SUMX2PY2" | "SUMXMY2" | "SWITCH" | "SYD" | "T" | "T.DIST" | "T.DIST.2T" | "T.DIST.RT" | "T.INV" | "T.INV.2T" | "T.TEST" | "TAN" | "TANH" | "TBILLEQ" | "TBILLPRICE" | "TBILLYIELD" | "TDIST" | "TEXT" | "TEXTJOIN" | "TIME" | "TIMEVALUE" | "TINV" | "TODAY" | "TRANSPOSE" | "TREND" | "TRIM" | "TRIMMEAN" | "TRUE" | "TRUNC" | "TTEST" | "TYPE" | "UNICHAR" | "UNICODE" | "UNIQUE" | "UPPER" | "VALUE" | "VALUETOTEXT" | "VAR" | "VAR.P" | "VAR.S" | "VARA" | "VARP" | "VARPA" | "VDB" | "VLOOKUP" | "WEBSERVICE" | "WEEKDAY" | "WEEKNUM" | "WEIBULL" | "WEIBULL.DIST" | "WORKDAY" | "WORKDAY.INTL" | "XIRR" | "XLOOKUP" | "XMATCH" | "XNPV" | "XOR" | "YEAR" | "YEARFRAC" | "YIELD" | "YIELDDISC" | "YIELDMAT" | "Z.TEST" | "ZTEST">;
export type BuiltInFormulas = typeof BUILT_IN_FUNCTION_SET extends Set<infer T> ? T : never;
export declare const CHART_TYPE_LIST: Array<{
    value: ChartType;
    label: string;
}>;
export declare const NUMBER_FORMAT_LIST: Array<{
    formatCode: string;
    id: number;
}>;
export declare const getFormatCode: (id: number) => string;
